### ISSUE TITLE
Kube config is not set

### ISSUE THREAD

**Issue by iamvishnuks** [adfolks/aksctl#20]
Once the cluster is created, kubeconfig is not configured.

**Comment by iamvishnuks** [comment]
@ashmilhussain anyone working on this?

**Comment by ashmilhussain** [comment]
Our team is working on it and we will update you soon

**Comment by iamvishnuks** [comment]
cool

**Comment by saikrishnans** [comment]
**Waiting for the update**

**Comment by ashmilhussain** [comment]
The issue is resolved kindly check and feel free to reopen the issue if it doesn't work

**Comment by iamvishnuks** [comment]
Fixed!! #26
