### ISSUE TITLE
Adding support for generating SSH public and private key files if missing

### ISSUE THREAD

**Issue by hkamel** [adfolks/aksctl#31]
The current version assuming SSH keys are present and the cluster creation will fail on basic usage scenarios.

**Steps To Reproduce**
Without SSH keys, run _**aksctl create cluster**_

cluster creation will fail with the error: _**Failed :exit status 1: ERROR: An RSA key file or key value must be supplied to SSH Key Value. You can use --generate-ssh-keys to let CLI generate one for you**_

![image](https://user-images.githubusercontent.com/5002831/69442898-c750ad80-0d66-11ea-8bec-c9924411295d.png)

**Expected behavior**
on the basic usage scenarios, it's recommended to auto-generate the keys using --generate-ssh-keys. If the user want more customization, then the template file would be the recommended way.

**aksctl version**
[v0.1.0](https://github.com/adfolks/aksctl/releases/tag/v0.1.0)

**Comment by ashmilhussain** [comment]
Thanks for addressing this issue, we are working on the fix

**Comment by hkamel** [comment]
@ashmilhussain I have fixed it already will push a PR soon

**Comment by iamvishnuks** [comment]
It expected ssh keys to be there in C:\Documents and Settings\Username\.ssh\, adding --generate-ssh-keys flag will fix the issue.

**Comment by hkamel** [comment]
> It expected ssh keys to be there in C:\Documents and Settings\Username.ssh, adding --generate-ssh-keys flag will fix the issue.

@vishnu-ks In the basic scenarios, it should not be the default behavior and you can't add --generate-ssh-keys directly to aksctl tool since you manage the extra configs in the code.

**Comment by iamvishnuks** [comment]
Yes.. saw your code  👍😊 . Closing this issue since it is fixed!!
