### ISSUE TITLE
aksctl should remove kubeconfig content or overwrite the cluster after a prompt

### ISSUE THREAD

**Issue by anoopl** [adfolks/aksctl#36]
I created a cluster with default.yaml and deleted the cluster. 
Now on creating a new cluster I get the following error:

```
Cluster Created
Fetching Credentials ........
This would take a few minutes...
---------------------------------
Failed :exit status 1: ERROR: A different object named cluster already exists in clusters in your kubeconfig file.

Updated Kubeconfig`
```
So aksctl should have an option to remove the cluster config from kubeconfig. Also there should be a command to to get kubeconfig file even after cluster creation which can be used on failure cases like this.

**Comment by ashmilhussain** [comment]
This issue is resolved in PR # 39, please verify and get back if the issue remains

**Comment by anoopl** [comment]
Thanks!!!
 will test and let you know

**Comment by ashmilhussain** [comment]
try get credential -n <cluster name> -g <resource group name> to generate kubeconfig again
