### ISSUE TITLE
Install with chocolatey for windows machines

### ISSUE THREAD

**Issue by torosgo** [adfolks/aksctl#55]
It would be nice feature to be able to install aksctl on windows machines using chocolatey package manager.

`choco install aksctl`

https://chocolatey.org/docs/CreatePackagesQuickStart
https://chocolatey.org/docs/create-packages
https://chocolatey.org/blog/create-chocolatey-packages

**Comment by iamvishnuks** [comment]
Yes we will add it. We are planning to release the next version this weekend. Mostly tomorrow.👍

**Comment by iamvishnuks** [comment]
https://chocolatey.org/packages/aksctl/0.2.0
Published in choclatey!! :-)
